### ISSUE TITLE
Covenant abilities showing up unconditionally, if you toggle all, all 4 show up for each arena enemy

### ISSUE THREAD

**Issue by SweepyBoop** [vendethiel/LibCooldownTracker-10#15]
Hi Vendethiel,

Should covenant abilities have the "talent=true" condition for it to only show up after first usage?
Unless you have another way to detect players' covenant choices before it's used.

**Comment by vendethiel** [comment]
Do you have "hide talents before they're detected" unchecked? Because this never happened to me (it shouldn't work like that anyway, I agree with that).

**Comment by SweepyBoop** [comment]
I always have "Hide talents until detected" checked.

I'm talking about the class covenant abilities, such as Ashen Hollow, Divine Toll for paladin, if I check both, both would show up from the beginning to the end of the match, versus nothing shows in the beginning and the correct one shows up after first usage.

I'll test if adding "talent = true" to the covenant abilities address that issue (or are you planning another condition specifically for covenants?)

**Comment by SweepyBoop** [comment]
![Covenant](https://user-images.githubusercontent.com/78008331/106217427-8ed51b00-6218-11eb-91f6-f6845cecfb6e.png)

**Comment by SweepyBoop** [comment]
Okay I updated the addon from CurseForged, I think it's working fine now.
Thanks for the great work!
