### ISSUE TITLE
Covenant ability tracking stops working, nothing shows up now

### ISSUE THREAD

**Issue by SweepyBoop** [vendethiel/LibCooldownTracker-10#17]
Hi, I pulled the latest code and put the folder into my addon but now all the covenants stopped working, nothing shows up.
You mentioned you're currently doing some covenant refactor, could that be related? Maybe you're in the middle of the refactor and things won't work for a while.

**Comment by vendethiel** [comment]
Hi,

I pushed some commit in gladiusex a few days ago that work with this,did you pull it as well?

**Comment by SweepyBoop** [comment]
Okay after updating my gladiusEx it works well now, thanks!

**Comment by vendethiel** [comment]
Perfect then
