### ISSUE TITLE
2 shaman cooldowns

### ISSUE THREAD

**Issue by gobacktogo** [vendethiel/LibCooldownTracker-10#6]
-- Tremor Totem
LCT_SpellData[8143] = {
	class = "SHAMAN",
	duration = 10,
        cooldown = 60
}

and grounding totem is now a pvp talent for afaik all speccs instead of being only for resto resto.
is "talent = true" enough, or does it matter that it is a pvp talent?

-- Grounding Totem
LCT_SpellData[204336] = {
	class = "SHAMAN",
	duration = 3,
	talent = true,
	defensive = true,
        cooldown = 30
}

also, hex has a 30s cd instead of 45s.
-- Hex
LCT_SpellData[51514] = {
	class = "SHAMAN",
	cc = true,
	cooldown = 30
}

**Comment by vendethiel** [comment]
Doesn't matter if it's a pvp talent.

**Comment by vendethiel** [comment]
fixed locally

**Comment by kimurin** [comment]
> fixed locally

Still no tremor totem in the list.

**Comment by vendethiel** [comment]
« Locally » does mean « locally ».
